INSERT INTO USER_ROLE (ROLE, NAME) VALUES('ROLE_MANAGER', 'Manager');

ALTER TABLE USERS ENGINE=InnoDB;

ALTER TABLE TIMESHEET_LOCK ENGINE=InnoDB;

CREATE TABLE TIMESHEET_LOCK_EXCLUSION (
  LOCK_ID INT(11) NOT NULL,
  USER_ID INT(11) NOT NULL,
  PRIMARY KEY (LOCK_ID, USER_ID),
  INDEX IDX_LOCK_ID (LOCK_ID ASC),
  INDEX fk_TIMESHEET_LOCK_EXCLUSION_1_idx (USER_ID ASC),
  CONSTRAINT FK_EXCLUSION_USER
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_EXCLUSION_LOCK
  FOREIGN KEY (LOCK_ID)
  REFERENCES TIMESHEET_LOCK (LOCK_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE=InnoDB DEFAULT CHARSET=utf8;


UPDATE CONFIGURATION SET CONFIG_VALUE = '1.3.1' WHERE CONFIG_KEY = 'version';

