CREATE  TABLE TIMESHEET_LOCK (
  LOCK_ID INT NOT NULL AUTO_INCREMENT,
  DATE_START DATE NOT NULL ,
  DATE_END DATE NOT NULL ,
  NAME VARCHAR(255) NULL ,
  PRIMARY KEY (LOCK_ID) );
  
ALTER TABLE TIMESHEET_LOCK
ADD INDEX IDX_LOCK_RANGE (DATE_START ASC, DATE_END ASC) ;

UPDATE CONFIGURATION SET CONFIG_VALUE = '1.3' WHERE CONFIG_KEY = 'version';

