--
-- Modification for table `CUSTOMER`
--
alter table CUSTOMER add unique (CODE);
alter table CUSTOMER add unique (CODE, ACTIVE);

--
-- Modification for table `PROJECT`
--
alter table PROJECT add unique (PROJECT_CODE);
alter table PROJECT add unique (PROJECT_CODE, ACTIVE);

--
-- Modification for table `AUDIT`
--

alter table AUDIT rename AUDITLOG;

--
-- Modification for table `TIMESHEET_ENTRY`
--
DROP TABLE IF EXISTS `TIMESHEET_ENTRY`;
CREATE TABLE `TIMESHEET_ENTRY` (
  `ACTIVITY_ID` int(11) NOT NULL,
  `ENTRY_DATE` date NOT NULL,
  `UPDATE_DATE` TIMESTAMP,  
  `HOURS` float(9,3),
  `COMMENT` varchar(2048),
  PRIMARY KEY  (`ENTRY_DATE`,`ACTIVITY_ID`),
  KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `TIMESHEET_ENTRY_fk` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITIES` (`ACTIVITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure for table `ACTIVITIES`
--
DROP TABLE IF EXISTS `ACTIVITIES`;
CREATE TABLE `ACTIVITIES` (
  `ACTIVITY_ID` int(11) NOT NULL auto_increment,
  `CODE` varchar(128) default NULL,
  `NAME` varchar(255) NOT NULL,
  `DATE_START` date default NULL,
  `DATE_END` date default NULL,
  `ALLOTTED_HOURS` float(9,3) NOT NULL,
  `ACTIVE` char(1) character set latin1 NOT NULL default 'Y',
  `PROJECT_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY  (`ACTIVITY_ID`),
  UNIQUE KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `ACTIVITY_fk1` FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`),
  CONSTRAINT `ACTIVITY_fk2` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure for table `CUSTOMER_REVIEWERS`
--
DROP TABLE IF EXISTS `CUSTOMER_REVIEWERS`;
CREATE TABLE `CUSTOMER_REVIEWERS` (
  `USER_ID` int(11) NOT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`,`CUSTOMER_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_REVIEWERS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
  CONSTRAINT `CUSTOMER_REVIEWERS_fk2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure for table `CUSTOMER_REPORTERS`
--
DROP TABLE IF EXISTS `CUSTOMER_REPORTERS`;
CREATE TABLE `CUSTOMER_REPORTERS` (
  `USER_ID` int(11) NOT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`,`CUSTOMER_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_REPORTERS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
  CONSTRAINT `CUSTOMER_REPORTERS_fk2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure for table `APPROVAL_STATUSES`
--
DROP TABLE IF EXISTS `APPROVAL_STATUSES`;
CREATE TABLE `APPROVAL_STATUSES` (
  `APPROVALSTATUS_ID` int(11) NOT NULL auto_increment,
  `DATE_START` date default NULL,
  `DATE_END` date default NULL,
  `CUSTOMER_ID` int(10) NOT NULL,
  `USER_ID` int(10) NOT NULL,
  `STATUS` varchar(128) NOT NULL,
  `COMMENT_TEXT` varchar(2048) default NULL,
  PRIMARY KEY  (`APPROVALSTATUS_ID`),
  UNIQUE KEY `APPROVALSTATUS_ID` (`APPROVALSTATUS_ID`),
  CONSTRAINT `APPROVAL_STATUSES_fk1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `APPROVAL_STATUSES_fk2` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Table structure for table `USER_PREFERENCES`
--
DROP TABLE IF EXISTS `USER_PREFERENCES`;
CREATE TABLE `USER_PREFERENCES` (
  `USER_ID` int(11) NOT NULL,
  `USER_PREFERENCE_KEY` varchar(255) NOT NULL,
  `USER_PREFERENCE_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`USER_ID`, `USER_PREFERENCE_KEY`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `USER_PREFERENCES_fk` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Addition of new information for `USER_ROLE`
--

INSERT INTO `USER_ROLE` VALUES ('ROLE_CUSTOMERREVIEWER','Customer Reviewer');
INSERT INTO `USER_ROLE` VALUES ('ROLE_CUSTOMERREPORTER','Customer Reporter');
