DROP TABLE IF EXISTS AUDIT;
CREATE TABLE AUDIT (
	AUDIT_ID INT(11)  NOT NULL AUTO_INCREMENT,
	USER_ID INT(11) default NULL,
	USER_FULLNAME VARCHAR(256),
	AUDIT_DATE datetime,
	PAGE VARCHAR(256),
	ACTION VARCHAR(256),
	PARAMETERS VARCHAR(1024),
	SUCCESS char(1) character set latin1 NOT NULL,
	AUDIT_ACTION_TYPE VARCHAR(32),
  PRIMARY KEY  (AUDIT_ID),
  KEY `IDX_AUDIT_DATE` (`AUDIT_DATE`),
  KEY `IDX_AUDIT_USER` (`USER_FULLNAME`),
  KEY `IDX_AUDIT_ACTION_TYPE` (`AUDIT_ACTION_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

UPDATE CONFIGURATION SET CONFIG_VALUE = '0.8.3' WHERE CONFIG_KEY = 'version';

CREATE TABLE `CONFIGURATION_BIN` (
  `CONFIG_KEY` varchar(255) NOT NULL,
  `CONFIG_VALUE` longblob,
  `METADATA` varchar(255) default NULL,
  PRIMARY KEY  (`config_key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
