INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VALUE) VALUES('reminderEnabled', 'false');
INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VALUE) VALUES('reminderBody', 'Our records show that you have not posted your weekly hours online. Please be sure to post your hours by 5:30PM Friday.');
INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VALUE) VALUES('reminderTime', '* 30 17 * * FRI');
INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VALUE) VALUES('reminderSubject', 'Missing hours');
INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VALUE) VALUES('reminderMinimalHours', '32');

ALTER TABLE MAIL_LOG DROP FOREIGN KEY MAIL_LOG_fk;
ALTER TABLE MAIL_LOG DROP FOREIGN KEY MAIL_LOG_fk1;

DROP TABLE MAIL_TYPE;
DROP TABLE MAIL_LOG_ASSIGNMENT;

ALTER TABLE MAIL_LOG DROP COLUMN RESULT_MSG;
ALTER TABLE MAIL_LOG DROP COLUMN MAIL_TYPE_ID;
ALTER TABLE MAIL_LOG DROP COLUMN TO_USER_ID;
ALTER TABLE MAIL_LOG ADD COLUMN MAIL_EVENT VARCHAR(64);
ALTER TABLE MAIL_LOG ADD COLUMN MAIL_TO VARCHAR(255);
CREATE INDEX IDX_MAIL ON MAIL_LOG (MAIL_TO, MAIL_EVENT);

UPDATE CONFIGURATION SET CONFIG_VALUE = '1.4' WHERE CONFIG_KEY = 'version';

