ALTER TABLE TIMESHEET_ENTRY MODIFY HOURS DECIMAL(9, 3);

CREATE TABLE TIMESHEET_ENTRY_SEGMENT (
    ASSIGNMENT_ID INT(11) NOT NULL,
    ENTRY_DATE    DATE    NOT NULL,
    START_WORK_TIME TIMESTAMP NOT NULL,
    END_WORK_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ASSIGNMENT_ID, ENTRY_DATE, START_WORK_TIME),
    CONSTRAINT TIMESHEET_ENTRY_SEGMENT_ASSIGNMENT_ID_FK FOREIGN KEY (ASSIGNMENT_ID, ENTRY_DATE) REFERENCES TIMESHEET_ENTRY (ASSIGNMENT_ID, ENTRY_DATE)
)
ENGINE =InnoDB
DEFAULT CHARSET =utf8;