# WW: Should DROP tables in the REVERSE order that they were created in order not to violate the foreign key constraints.
DROP TABLE "CONFIGURATION_BIN";
DROP TABLE "USER_TO_USERROLE";
DROP TABLE "USER_ROLE";
DROP TABLE "TIMESHEET_ENTRY";
DROP TABLE "TIMESHEET_COMMENT";
DROP TABLE "MAIL_LOG_ASSIGNMENT";
DROP TABLE "PROJECT_ASSIGNMENT";
DROP TABLE "PROJECT_ASSIGNMENT_TYPE";
DROP TABLE "PROJECT";
DROP TABLE "MAIL_LOG";
DROP TABLE "USERS";
DROP TABLE "USER_DEPARTMENT";
DROP TABLE "MAIL_TYPE";
DROP TABLE "AUDIT";
DROP TABLE "CONFIGURATION";
DROP TABLE "CUSTOMER";