INSERT INTO USER_ROLE (ROLE, NAME) VALUES('ROLE_MANAGER', 'MANAGER');

CREATE TABLE TIMESHEET_LOCK_EXCLUSION (
   LOCK_ID INTEGER,
   USER_ID INTEGER,
   CONSTRAINT PK PRIMARY KEY (LOCK_ID, USER_ID) USING INDEX TABLESPACE PG_DEFAULT,
   CONSTRAINT FK_EXCL_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
   CONSTRAINT FK_EXCL_LOCK_ID FOREIGN KEY (LOCK_ID) REFERENCES TIMESHEET_LOCK (LOCK_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);

UPDATE CONFIGURATION SET CONFIG_VALUE = '1.3.1' WHERE CONFIG_KEY = 'version';
