ALTER TABLE TIMESHEET_ENTRY ALTER COLUMN HOURS TYPE DECIMAL(9, 3);

DROP TABLE IF EXISTS TIMESHEET_ENTRY_SEGMENT;
CREATE TABLE TIMESHEET_ENTRY_SEGMENT (
    ASSIGNMENT_ID INTEGER NOT NULL,
    ENTRY_DATE    TIMESTAMP NOT NULL,
    START_WORK_TIME TIMESTAMP NOT NULL,
    END_WORK_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ASSIGNMENT_ID, ENTRY_DATE, START_WORK_TIME),
    CONSTRAINT TIMESHEET_ENTRY_SEGMENT_ASSIGNMENT_ID_FK FOREIGN KEY (ASSIGNMENT_ID, ENTRY_DATE) REFERENCES TIMESHEET_ENTRY (ASSIGNMENT_ID, ENTRY_DATE) ON DELETE CASCADE
);
