/**
 * Created on Nov 11, 2006
 * Created by Thies Edeling
 * Copyright (C) 2005, 2006 te-con, All Rights Reserved.
 *
 * This Software is copyright TE-CON 2007. This Software is not open source by definition. The source of the Software is available for educational purposes.
 * TE-CON holds all the ownership rights on the Software.
 * TE-CON freely grants the right to use the Software. Any reproduction or modification of this Software, whether for commercial use or open source,
 * is subject to obtaining the prior express authorization of TE-CON.
 * thies@te-con.nl
 * TE-CON
 * Legmeerstraat 4-2h, 1058ND, AMSTERDAM, The Netherlands
 *
 */

package net.rrm.ehour.user.domain;

import net.rrm.ehour.domain.DomainObject;

import org.acegisecurity.GrantedAuthority;
import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * UserRole generated by hbm2java
 */
public class UserRole extends DomainObject<String, UserRole> implements GrantedAuthority
{

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 3806904191272349157L;
	private String 	role;
	private String	roleName;


	/**
	 * Minimal
	 *
	 */
	public UserRole()
	{
	}
	
	public UserRole(String role)
	{
		this.role = role;
	}

	public UserRole(String role, String roleName)
	{
		this.role = role;
		this.roleName = roleName;
		
	}

	public String getRoleName()
	{
		return roleName;
	}

	public void setRoleName(String roleName)
	{
		this.roleName = roleName;
	}

	public String getRole()
	{
		return role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	public String getAuthority()
	{
		return role;
	}
	
	/**
	 * 
	 */
	@Override
    public boolean equals(Object obj)
    {
    	boolean isEqual = false;
    	
        if (obj instanceof String)
        {
            isEqual = obj.equals(this.role);
        }
        else if (obj instanceof UserRole)
        {
        	isEqual = ((UserRole)obj).getRole().equals(this.role);
        }

        return isEqual;
    }	
    
    /**
     * 
     */
	@Override
    public int hashCode()
    {
    	return new HashCodeBuilder().append(role).toHashCode();
    }
	
    public String toString()
    {
    	return role;
    }

	@Override
	public String getPK()
	{
		return role;
	}

	/**
	 * @see java.lang.Comparable#compareTo(Object)
	 */
	public int compareTo(UserRole object)
	{
		return new CompareToBuilder()
			.append(this.role, object.role)
			.append(this.roleName, object.roleName).toComparison();
	}

}
