/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package net.rrm.ehour.domain;

// Generated Apr 7, 2007 1:08:18 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * MailLogAssignment generated by hbm2java
 */
public class MailLogAssignment extends MailLog
{

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = -6902873370377635410L;
	private ProjectAssignment projectAssignment;
	private Float bookedHours;
	private Date	bookDate;

	// Constructors

	/** default constructor */
	public MailLogAssignment()
	{
	}

	/** full constructor */
	public MailLogAssignment(MailType mailType, User toUser, Date timestamp, Boolean success, String resultMsg, ProjectAssignment projectAssignment)
	{
		super(mailType, toUser, timestamp, success, resultMsg);
		this.projectAssignment = projectAssignment;
	}

	// Property accessors
	public ProjectAssignment getProjectAssignment()
	{
		return this.projectAssignment;
	}

	public void setProjectAssignment(ProjectAssignment projectAssignment)
	{
		this.projectAssignment = projectAssignment;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object)
	{
		if (!(object instanceof MailLogAssignment))
		{
			return false;
		}
		
		MailLogAssignment rhs = (MailLogAssignment) object;
		return new EqualsBuilder()
			.appendSuper(super.equals(object))
			.append(this.getProjectAssignment(), rhs.getProjectAssignment())
			.isEquals();
	}

	/**
	 * @see java.lang.Comparable#compareTo(Object)
	 */
	public int compareTo(MailLogAssignment object)
	{
		return new CompareToBuilder()
			.append(this.getProjectAssignment(), object.getProjectAssignment())
			.toComparison();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode()
	{
		return new HashCodeBuilder(-1194418173, 1339254353)
				.appendSuper(super.hashCode())
				.append(this.getProjectAssignment())
				.toHashCode();
	}

	/**
	 * @return the bookDate
	 */
	public Date getBookDate()
	{
		return bookDate;
	}

	/**
	 * @param bookDate the bookDate to set
	 */
	public void setBookDate(Date bookDate)
	{
		this.bookDate = bookDate;
	}

	/**
	 * @return the bookedHours
	 */
	public Float getBookedHours()
	{
		return bookedHours;
	}

	/**
	 * @param bookedHours the bookedHours to set
	 */
	public void setBookedHours(Float bookedHours)
	{
		this.bookedHours = bookedHours;
	}

}
