package net.rrm.ehour.user.domain;

// Generated Sep 26, 2006 11:58:17 PM by Hibernate Tools 3.2.0.beta7


/**
 * Organisation generated by hbm2java
 */
public class Organisation implements java.io.Serializable
{

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 7802944013593352L;

	/**
	 * @uml.property  name="organisationId"
	 */
	private Integer organisationId;

	/**
	 * @uml.property  name="name"
	 */
	private String name;

	/**
	 * @uml.property  name="code"
	 */
	private String code;

	// Constructors

	/** default constructor */
	public Organisation()
	{
	}

	/** minimal constructor */
	public Organisation(Integer organisationId, String name, String code)
	{
		this.organisationId = organisationId;
		this.name = name;
		this.code = code;
	}


	// Property accessors
	/**
	 * @return  the organisationId
	 * @uml.property  name="organisationId"
	 */
	public Integer getOrganisationId()
	{
		return this.organisationId;
	}

	/**
	 * @param organisationId  the organisationId to set
	 * @uml.property  name="organisationId"
	 */
	public void setOrganisationId(Integer organisationId)
	{
		this.organisationId = organisationId;
	}

	/**
	 * @return  the name
	 * @uml.property  name="name"
	 */
	public String getName()
	{
		return this.name;
	}

	/**
	 * @param name  the name to set
	 * @uml.property  name="name"
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * @return  the code
	 * @uml.property  name="code"
	 */
	public String getCode()
	{
		return this.code;
	}

	/**
	 * @param code  the code to set
	 * @uml.property  name="code"
	 */
	public void setCode(String code)
	{
		this.code = code;
	}

}
