ALTER TABLE TIMESHEET_ENTRY ADD UPDATE_DATE TIMESTAMP;

INSERT INTO CONFIGURATION VALUES('smtpPort', '25');
UPDATE CONFIGURATION SET CONFIG_VALUE = 'en,nl,fr,it' WHERE CONFIG_KEY = 'availableTranslations';
UPDATE CONFIGURATION SET CONFIG_VALUE = '0.8' WHERE CONFIG_KEY = 'version';


