ALTER TABLE TIMESHEET_ENTRY ADD DISPLAY_ORDER INT NOT NULL DEFAULT 1;
ALTER TABLE TIMESHEET_ENTRY MODIFY HOURS float(9,3) null;
ALTER TABLE TIMESHEET_ENTRY ADD COMMENT varchar(2048);

UPDATE CONFIGURATION SET CONFIG_VALUE = '0.7.2' WHERE CONFIG_KEY = 'version';
