ALTER TABLE TIMESHEET_ENTRY ADD UPDATE_DATE TIMESTAMP;

UPDATE CONFIGURATION SET CONFIG_VALUE = 'en,nl,fr' WHERE CONFIG_KEY = 'availableTranslations';
UPDATE CONFIGURATION SET CONFIG_VALUE = '0.8' WHERE CONFIG_KEY = 'version';


