ALTER TABLE USER RENAME USERS;

INSERT INTO CONFIGURATION VALUES('demoMode', 'false');
INSERT INTO CONFIGURATION VALUES('version', '0.7');

ALTER TABLE TIMESHEET_COMMENT MODIFY COMMENT VARCHAR(2048);