DROP TABLE IF EXISTS AUDIT;
CREATE TABLE AUDIT (
        AUDIT_ID INT(11)  NOT NULL AUTO_INCREMENT,
        USER_ID INT(11) default NULL,
	USER VARCHAR(256),
        AUDIT_DATE datetime,
        ACTION VARCHAR(256),
        PARAMETERS VARCHAR(1024),
        SUCCESS char(1) character set latin1 NOT NULL,
        AUDIT_ACTION_TYPE VARCHAR(32),
  PRIMARY KEY  (AUDIT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

