# REMOVE REFERENCES TO ASSIGNMENT IN MAIL_LOG
ALTER TABLE MAIL_LOG_ASSIGNMENT RENAME TO MAIL_LOG_ACTIVITY;
ALTER TABLE MAIL_LOG_ACTIVITY DROP CONSTRAINT MAIL_LOG_ASSIGNMENT_FK1;
ALTER TABLE MAIL_LOG_ACTIVITY RENAME COLUMN PROJECT_ASSIGNMENT_ID TO ACTIVITY_ID;

# DROP PROJECT_ASSIGNMENT AND TYPE TABLE
DROP TABLE PROJECT_ASSIGNMENT;
DROP TABLE PROJECT_ASSIGNMENT_TYPE;
