package net.rrm.ehour.mail.domain;

// Generated Apr 7, 2007 1:08:18 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import net.rrm.ehour.project.domain.ProjectAssignment;
import net.rrm.ehour.user.domain.User;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * MailLogAssignment generated by hbm2java
 */
public class MailLogAssignment extends MailLog
{

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = -6902873370377635410L;
	private ProjectAssignment projectAssignment;

	// Constructors

	/** default constructor */
	public MailLogAssignment()
	{
	}

	/** full constructor */
	public MailLogAssignment(MailType mailType, User toUser, Date timestamp, Boolean success, String resultMsg, ProjectAssignment projectAssignment)
	{
		super(mailType, toUser, timestamp, success, resultMsg);
		this.projectAssignment = projectAssignment;
	}

	// Property accessors
	public ProjectAssignment getProjectAssignment()
	{
		return this.projectAssignment;
	}

	public void setProjectAssignment(ProjectAssignment projectAssignment)
	{
		this.projectAssignment = projectAssignment;
	}

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object)
	{
		if (!(object instanceof MailLogAssignment))
		{
			return false;
		}
		MailLogAssignment rhs = (MailLogAssignment) object;
		return new EqualsBuilder().appendSuper(super.equals(object)).append(this.projectAssignment, rhs.projectAssignment).isEquals();
	}

	/**
	 * @see java.lang.Comparable#compareTo(Object)
	 */
	public int compareTo(MailLogAssignment object)
	{
		return new CompareToBuilder().append(this.projectAssignment, object.projectAssignment).toComparison();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode()
	{
		return new HashCodeBuilder(-1194418173, 1339254353).appendSuper(super.hashCode()).append(this.projectAssignment).toHashCode();
	}

}
