<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ page contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<title><tiles:getAsString name="pageTitle" /></title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" type="text/css" href="<c:url value="/css/ehourMain.jsp" />"  />
		<link rel="stylesheet" type="text/css" href="<c:url value="/css/ehourReport.jsp" />"  />
		
		<script>
			function setReportName()
			{
			}
		</script>
	</head>

<body onLoad="window.print()">

<br><br>
<center>
	
<div id="reportTarget">
		<tiles:insert attribute="reportTile" />
</div>

<br>
<div class="ReportPrintFooter">
	Report generated by eHour - http://www.ehour.nl/
</div>
</center>

</body>

</html>
